//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerType
    {
        public AnswerType()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
